# Generated by Django 5.2.16 on 2026-10-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0032_alter_agent_event_id_alter_agent_mobile_and_more'),
        ('event_referral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreferralcampaign',
            name='page_instructions',
            field=models.TextField(blank=True, default='Welcome to Paldi! Register below, preview your agent card and profile website, then share your link. Refer 5 agents who complete payment within 48 hours to unlock your Basic plan.'),
        ),
        migrations.AlterField(
            model_name='eventreferralcampaign',
            name='page_title',
            field=models.CharField(default='Paldi Registration', max_length=255),
        ),
        migrations.AddIndex(
            model_name='eventreferral',
            index=models.Index(fields=['participant', 'state'], name='ev_ref_part_state_idx'),
        ),
        migrations.AddIndex(
            model_name='eventreferral',
            index=models.Index(fields=['participant', 'counts'], name='ev_ref_part_counts_idx'),
        ),
    ]
