INSURANCE_COMPANIES = {
    "health": [
        "Aditya Birla Health Insurance Co. Limited",
        "Care Health Insurance Ltd. (formerly Religare Health Insurance)",
        "Galaxy Health and Allied Insurance Company Limited",
        "ManipalCigna Health Insurance Company Limited",
        "Niva Bupa Health Insurance Company Limited (formerly Max Bupa)",
        "Reliance Health Insurance Ltd.",
        "Star Health & Allied Insurance Co. Ltd. (India's first standalone health insurer)",
        "Narayana Health Insurance Company Limited",
        "Acko General Insurance Limited",
        "Agriculture Insurance Company of India Limited",
        "Bajaj General Insurance Limited",
        "Cholamandalam MS General Insurance Company Limited",
        "ECGC Limited",
        "Generali Central Insurance Company Limited",
        "Go Digit General Insurance Limited",
        "HDFC ERGO General Insurance Company Limited",
        "ICICI LOMBARD General Insurance Company Limited",
        "IFFCO TOKIO General Insurance Company Limited",
        "Zurich Kotak General Insurance Company Limited",
        "Kshema General Insurance Limited",
        "Liberty General Insurance Limited",
        "Magma General Insurance Limited",
        "National Insurance Company Limited",
        "Navi General Insurance Limited",
        "Raheja QBE General Insurance Co. Ltd.",
        "Reliance General Insurance Company Limited",
        "Royal Sundaram General Insurance Company Limited",
        "SBI General Insurance Company Limited",
        "Shriram General Insurance Company Limited",
        "Tata AIG General Insurance Company Limited",
        "The New India Assurance Company Limited",
        "The Oriental Insurance Company Limited",
        "United India Insurance Company Limited",
        "Universal Sompo General Insurance Company Limited",
        "Zuna General Insurance Ltd."
    ],
    "life": [
        "Life Insurance Corporation of India",
        "Axis Max Life Insurance Limited",
        "HDFC Life Insurance Company Limited",
        "ICICI Prudential Life Insurance Company Limited",
        "Kotak Mahindra Life Insurance Company Limited",
        "Aditya Birla SunLife Insurance Company Limited",
        "TATA AIA Life Insurance Company Limited",
        "SBI Life Insurance Company Limited",
        "Bajaj Life Insurance Limited",
        "PNB MetLife India Insurance Company Limited",
        "Reliance Nippon Life Insurance Company Limited",
        "Aviva Life Insurance Company India Limited",
        "Sahara India Life Insurance Company Limited",
        "Shriram Life Insurance Company Limited",
        "Bharti AXA Life Insurance Company Limited",
        "Generali Central Life Insurance Company Limited",
        "Ageas Federal Life Insurance Company Limited",
        "Canara HSBC Life Insurance Company Limited",
        "Bandhan Life Insurance Limited",
        "Pramerica Life Insurance Company Limited",
        "Star Union Dai-Ichi Life Insurance Company Limited",
        "IndiaFirst Life Insurance Company Limited",
        "Edelweiss Life Insurance Company Limited",
        "CreditAccess Life Insurance Limited",
        "Acko Life Insurance Limited",
        "Go Digit Life Insurance Limited"
    ],
    "motor": [
        "Acko General Insurance Limited",
        "Agriculture Insurance Company of India Limited",
        "Bajaj General Insurance Limited",
        "Cholamandalam MS General Insurance Company Limited",
        "ECGC Limited",
        "Generali Central Insurance Company Limited",
        "Go Digit General Insurance Limited",
        "HDFC ERGO General Insurance Company Limited",
        "ICICI LOMBARD General Insurance Company Limited",
        "IFFCO TOKIO General Insurance Company Limited",
        "Zurich Kotak General Insurance Company Limited",
        "Kshema General Insurance Limited",
        "Liberty General Insurance Limited",
        "Magma General Insurance Limited",
        "National Insurance Company Limited",
        "Navi General Insurance Limited",
        "Raheja QBE General Insurance Co. Ltd.",
        "Reliance General Insurance Company Limited",
        "Royal Sundaram General Insurance Company Limited",
        "SBI General Insurance Company Limited",
        "Shriram General Insurance Company Limited",
        "Tata AIG General Insurance Company Limited",
        "The New India Assurance Company Limited",
        "The Oriental Insurance Company Limited",
        "United India Insurance Company Limited",
        "Universal Sompo General Insurance Company Limited",
        "Zuna General Insurance Ltd."
    ],
    "sme": [
        "Acko General Insurance Limited",
        "Agriculture Insurance Company of India Limited",
        "Bajaj General Insurance Limited",
        "Cholamandalam MS General Insurance Company Limited",
        "ECGC Limited",
        "Generali Central Insurance Company Limited",
        "Go Digit General Insurance Limited",
        "HDFC ERGO General Insurance Company Limited",
        "ICICI LOMBARD General Insurance Company Limited",
        "IFFCO TOKIO General Insurance Company Limited",
        "Zurich Kotak General Insurance Company Limited",
        "Kshema General Insurance Limited",
        "Liberty General Insurance Limited",
        "Magma General Insurance Limited",
        "National Insurance Company Limited",
        "Navi General Insurance Limited",
        "Raheja QBE General Insurance Co. Ltd.",
        "Reliance General Insurance Company Limited",
        "Royal Sundaram General Insurance Company Limited",
        "SBI General Insurance Company Limited",
        "Shriram General Insurance Company Limited",
        "Tata AIG General Insurance Company Limited",
        "The New India Assurance Company Limited",
        "The Oriental Insurance Company Limited",
        "United India Insurance Company Limited",
        "Universal Sompo General Insurance Company Limited",
        "Zuna General Insurance Ltd."
    ]
}
