# Generated by Django 5.2.16 on 2026-07-29 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentApprovalRequest',
        ),
        migrations.RemoveField(
            model_name='insuranceprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='insuranceprofile',
            name='sub_role',
        ),
        migrations.AddField(
            model_name='insuranceprofile',
            name='insurance_sub_role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('onboarding', 'Onboarding'), ('sales', 'Sales'), ('accounts', 'Accounts')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceprofile',
            name='insurance_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='InsuranceCompany',
        ),
    ]
