# Generated by Django 5.2.16 on 2026-08-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatmessage_agent_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='latencylog',
            name='groq_limit_tokens',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='latencylog',
            name='groq_remaining_tokens',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='latencylog',
            name='groq_reset_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='latencylog',
            name='provider_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='latencylog',
            name='used_completion_tokens',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='latencylog',
            name='used_prompt_tokens',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
