# Generated by Django 6.0.2 on 2026-07-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_didyouknowslide_heroproducttile_heroslide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField(blank=True, null=True)),
                ('insurer', models.CharField(blank=True, max_length=255, null=True)),
                ('insurer_type', models.CharField(blank=True, max_length=50, null=True)),
                ('pan', models.CharField(blank=True, max_length=20, null=True)),
                ('agent_name', models.CharField(max_length=255)),
                ('agency_code', models.CharField(blank=True, max_length=50, null=True)),
                ('blacklisted_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(default='IRDAI', max_length=100)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blacklisted_agents',
                'ordering': ['agent_name'],
                'managed': False,
            },
        ),
    ]
