# Generated by Django 6.0.2 on 2026-07-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blacklistedagent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistedagent',
            options={'managed': True, 'ordering': ['agent_name']},
        ),
    ]
