# Generated by Django 5.2.16 on 2026-07-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_blacklistedagent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistedagent',
            options={'managed': False, 'ordering': ['agent_name']},
        ),
    ]
