# Generated by Django 5.2.16 on 2026-09-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_upcoming_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingfeature',
            name='visible_to',
            field=models.CharField(choices=[('all', 'All Plans (Starter & Professional)'), ('starter', "Starter's Plan Only"), ('professional', "Professional's Plan Only")], default='all', max_length=20),
        ),
    ]
