# Generated by Django 5.2.16 on 2026-10-04 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0035_agent_fks_without_db_constraint'),
        ('home', '0010_alter_upcomingfeature_visible_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleReviewConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Agent-level ON/OFF switch for Google Reviews display')),
                ('google_review_url', models.URLField(blank=True, default='', help_text='Direct URL to write a review on Google', max_length=500)),
                ('google_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Overall Google Rating, e.g. 4.8', max_digits=3, null=True)),
                ('google_review_count', models.IntegerField(default=0, help_text='Total count of reviews on Google')),
                ('google_place_name', models.CharField(blank=True, default='', help_text='Business or Agent name as listed on Google', max_length=255)),
                ('cached_reviews', models.JSONField(blank=True, default=list, help_text='Up to 5 featured Google reviews entered by agent')),
                ('google_review_clicks', models.IntegerField(default=0, help_text='Total clicks on Review on Google CTA')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='google_review_config', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Google Review Config',
                'verbose_name_plural': 'Google Review Configs',
                'db_table': 'agent_google_review_configs',
                'managed': True,
            },
        ),
    ]
