# Generated by Django 5.2.16 on 2026-10-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_googlereviewconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkOgSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text="URL path, e.g. '/' or '/agent/registration/' or '/events/paldi/'", max_length=240, unique=True)),
                ('image', models.CharField(help_text='Absolute URL or /media/ path to the OG image', max_length=500)),
                ('title', models.CharField(blank=True, default='', help_text='Custom OG Title (optional)', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Custom OG Description (optional)')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this OG preview rule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Link OG Setting',
                'verbose_name_plural': 'Link OG Settings',
                'db_table': 'link_og_settings',
                'ordering': ['path'],
            },
        ),
    ]
