# Generated by Django 5.2.16 on 2026-09-10 16:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0025_subscriptionplan_display_fields_safe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionshipCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PadosiAgent Referral Championship', max_length=255)),
                ('slug', models.SlugField(default='championship-2026', max_length=100, unique=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('paused', 'Paused'), ('ended', 'Ended'), ('archived', 'Archived')], default='live', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('pricing_config', models.JSONField(blank=True, default=dict, help_text='\n    {\n      "digital": {"regular_price": 1999, "campaign_price": 999, "renewal_price": 1999, "name": "Digital Visibility"},\n      "professional": {"regular_price": 9999, "campaign_price": 4999, "renewal_price": 9999, "name": "Professional Visibility"},\n      "discount_percent": 50\n    }\n    ')),
                ('unlock_config', models.JSONField(blank=True, default=dict, help_text='\n    {\n      "min_profile_percent": 80,\n      "min_reviews": 10\n    }\n    ')),
                ('social_channels', models.JSONField(blank=True, default=list, help_text='List of social channels to follow')),
                ('google_review_url', models.URLField(blank=True, default='https://g.page/r/padosiagent/review', max_length=500)),
                ('rules', models.TextField(blank=True, default='First valid referral attribution wins. Verified and Paid accounts count as qualifying.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'championship_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChampionshipGoogleReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('prompt_shown_at', models.DateTimeField(auto_now_add=True)),
                ('link_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'championship_google_review_logs',
            },
        ),
        migrations.CreateModel(
            name='ChampionshipScratchUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('draft_id', models.IntegerField(blank=True, null=True)),
                ('is_revealed', models.BooleanField(default=False)),
                ('revealed_discount_pct', models.IntegerField(default=25)),
                ('final_unlocked_pct', models.IntegerField(default=50)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'championship_scratch_unlocks',
            },
        ),
        migrations.CreateModel(
            name='ChampionshipAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referral_championship.championshipcampaign')),
            ],
            options={
                'db_table': 'championship_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChampionshipParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('profile_completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviews_completed_at', models.DateTimeField(blank=True, null=True)),
                ('qualifying_referrals_count', models.IntegerField(db_index=True, default=0)),
                ('current_rank', models.IntegerField(db_index=True, default=0)),
                ('last_qualification_time', models.DateTimeField(blank=True, null=True)),
                ('is_fraud_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='championship_participations', to='agents.agent')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='referral_championship.championshipcampaign')),
            ],
            options={
                'db_table': 'championship_participants',
                'ordering': ['-qualifying_referrals_count', 'last_qualification_time'],
                'unique_together': {('campaign', 'agent')},
            },
        ),
        migrations.CreateModel(
            name='ChampionshipReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.CharField(db_index=True, max_length=50)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_params', models.JSONField(blank=True, default=dict)),
                ('registration_state', models.CharField(choices=[('started', 'Started'), ('submitted', 'Submitted'), ('verification_pending', 'Verification Pending'), ('verified', 'Verified'), ('plan_selected', 'Plan Selected'), ('payment_pending', 'Payment Pending'), ('paid', 'Paid'), ('active', 'Active'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('fraud_blocked', 'Fraud Blocked')], default='started', max_length=50)),
                ('is_qualifying', models.BooleanField(db_index=True, default=False)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('fraud_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='referral_championship.championshipcampaign')),
                ('referred_agent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='championship_attributions', to='agents.agent')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='referral_championship.championshipparticipant')),
            ],
            options={
                'db_table': 'championship_referrals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChampionshipFraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('flagged', 'Flagged'), ('suspended', 'Suspended'), ('rejected', 'Rejected'), ('reversed', 'Reversed'), ('restored', 'Restored'), ('blocked', 'Blocked')], default='flagged', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to='referral_championship.championshipparticipant')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referral_championship.championshipreferral')),
            ],
            options={
                'db_table': 'championship_fraud_flags',
            },
        ),
        migrations.CreateModel(
            name='ChampionshipRewardSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.IntegerField(help_text='Referrals needed to unlock this slab')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reward_type', models.CharField(choices=[('membership_fee_back', 'Membership Fee Back'), ('plan_upgrade', 'Plan Upgrade (Pro 12M)'), ('silver', '25g Silver Coin'), ('gold', '1g Gold Coin'), ('domestic_trip', 'Solo Domestic Trip'), ('international_trip', 'Solo International Trip'), ('lucky_draw_tier1', 'Lucky Draw Tier 1'), ('lucky_draw_tier2', 'Lucky Draw Tier 2'), ('lucky_draw_tier3', 'Lucky Draw Tier 3'), ('family_trip', 'Family International Trip (Top 3)'), ('custom', 'Custom Reward')], max_length=50)),
                ('badge_icon', models.CharField(default='fa-gift', max_length=100)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('winner_limit', models.IntegerField(default=0, help_text='0 means unlimited')),
                ('dispatch_date_default', models.DateField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_slabs', to='referral_championship.championshipcampaign')),
            ],
            options={
                'db_table': 'championship_reward_slabs',
                'ordering': ['threshold', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ChampionshipSocialAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('platform', models.CharField(max_length=50)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referral_championship.championshipparticipant')),
            ],
            options={
                'db_table': 'championship_social_actions',
            },
        ),
        migrations.CreateModel(
            name='ChampionshipLeaderboardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(db_index=True)),
                ('referral_count', models.IntegerField(db_index=True)),
                ('tie_breaker_ts', models.DateTimeField(blank=True, null=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral_championship.championshipcampaign')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral_championship.championshipparticipant')),
            ],
            options={
                'db_table': 'championship_leaderboard_cache',
                'ordering': ['rank'],
                'unique_together': {('campaign', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='ChampionshipRewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('verification', 'Verification'), ('approved', 'Approved'), ('processing', 'Processing'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='unlocked', max_length=50)),
                ('claim_data', models.JSONField(blank=True, default=dict, help_text='Stores voucher provider (amazon/flipkart), address, etc.')),
                ('courier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='referral_championship.championshipparticipant')),
                ('reward_slab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='referral_championship.championshiprewardslab')),
            ],
            options={
                'db_table': 'championship_reward_claims',
                'ordering': ['-created_at'],
                'unique_together': {('participant', 'reward_slab')},
            },
        ),
    ]
