# Generated by Django 5.2.16 on 2026-09-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_championship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championshipcampaign',
            name='pricing_config',
            field=models.JSONField(blank=True, default=dict, help_text='\n    {\n      "digital": {"regular_price": 1999, "campaign_price": 999, "renewal_price": 1999, "name": "Starter\'s Plan"},\n      "professional": {"regular_price": 9999, "campaign_price": 4999, "renewal_price": 9999, "name": "Professional\'s Plan"},\n      "discount_percent": 50\n    }\n    '),
        ),
    ]
