# Generated by Django 6.0.2 on 2026-07-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdraft',
            name='arn_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agentdraft',
            name='euin_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agentdraft',
            name='investment_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentdraft',
            name='investment_valid_till',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentdraft',
            name='license_valid_till',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='arn_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='euin_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='investment_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='investment_valid_till',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='license_valid_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
