# Generated by Django 6.0.2 on 2026-07-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentdraft_arn_number_agentdraft_euin_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='blacklist_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='blacklist_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='blacklisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
