# Generated by Django 6.0.2 on 2026-07-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_blacklist_reason_agent_blacklist_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='insurance_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
