# Generated by Django 5.2.16 on 2026-07-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agent_insurance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='amfi_license_doc',
            field=models.FileField(blank=True, null=True, upload_to='app/public/investment/'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='irdai_license_doc',
            field=models.FileField(blank=True, null=True, upload_to='app/public/insurance/'),
        ),
    ]
