# Generated by Django 5.2.16 on 2026-07-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agent_insurance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='gbp_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='gbp_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='gbp_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
