# Generated by Django 5.2.16 on 2026-07-23 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agentprofile_gbp_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentBioGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('prompt_version', models.CharField(default='v1.0', max_length=50)),
                ('llm_model', models.CharField(default='llama-3.3-70b-versatile', max_length=100)),
                ('generation_time', models.FloatField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='success', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='bio_generation_logs', to='agents.agent')),
            ],
            options={
                'db_table': 'agent_bio_generation_logs',
                'ordering': ['-generated_at'],
            },
        ),
    ]
