# Generated by Django 5.2.16 on 2026-07-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agentprofile_license_docs'),
        ('agents', '0006_agentprofile_bio_generation_logs'),
    ]

    operations = [
    ]
