# Generated by Django 5.2.16 on 2026-07-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_merge_20260725_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='is_card_visible',
            field=models.BooleanField(default=True),
        ),
    ]
