# Generated by Django 5.2.16 on 2026-07-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agentprofile_is_card_visible'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='agentprofile',
                    name='is_profile_visible',
                    field=models.BooleanField(default=True),
                ),
                migrations.AddField(
                    model_name='agentprofile',
                    name='show_achievements',
                    field=models.BooleanField(default=True),
                ),
                migrations.AddField(
                    model_name='agentprofile',
                    name='show_certificates',
                    field=models.BooleanField(default=True),
                ),
                migrations.AddField(
                    model_name='agentprofile',
                    name='show_reviews',
                    field=models.BooleanField(default=True),
                ),
            ]
        )
    ]
