# Generated by Django 5.2.16 on 2026-07-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_agentprofile_is_profile_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='career_highlights',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
