# Generated by Django 5.2.16 on 2026-07-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_agent_onboarded_by'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='AgentBackup',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('user_id', models.IntegerField(blank=True, null=True)),
                        ('event_id', models.IntegerField(blank=True, null=True)),
                        ('distributor_id', models.IntegerField(blank=True, null=True)),
                        ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                        ('email', models.EmailField(blank=True, max_length=254, null=True)),
                        ('google_id', models.CharField(blank=True, max_length=255, null=True)),
                        ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                        ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                        ('registration_step', models.IntegerField(blank=True, null=True)),
                        ('agent_pincode', models.CharField(blank=True, max_length=6, null=True)),
                        ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                        ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                        ('plan_type', models.CharField(blank=True, max_length=50, null=True)),
                        ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                        ('upgrade_discount_percent', models.IntegerField(blank=True, null=True)),
                        ('referred_by_code', models.CharField(blank=True, max_length=50, null=True)),
                        ('referral_reward_type', models.CharField(blank=True, max_length=50, null=True)),
                        ('referral_reward_claimed', models.BooleanField(default=False)),
                        ('status', models.CharField(blank=True, max_length=50, null=True)),
                        ('is_approved', models.BooleanField(default=False)),
                        ('approved_at', models.DateTimeField(blank=True, null=True)),
                        ('badge', models.CharField(blank=True, max_length=255, null=True)),
                        ('admin_notes', models.TextField(blank=True, null=True)),
                        ('registration_draft', models.JSONField(blank=True, null=True)),
                        ('user_types', models.JSONField(blank=True, null=True)),
                        ('insurance_companies', models.JSONField(blank=True, null=True)),
                        ('experience_range', models.CharField(blank=True, max_length=50, null=True)),
                        ('client_base', models.CharField(blank=True, max_length=50, null=True)),
                        ('achievement_photo_limit', models.PositiveSmallIntegerField(blank=True, null=True)),
                        ('profession', models.CharField(blank=True, max_length=255, null=True)),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                        ('updated_at', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'agent_backup',
                        'managed': True,
                    },
                ),
                migrations.AddField(
                    model_name='agent',
                    name='google_id',
                    field=models.CharField(blank=True, max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name='agent',
                    name='referral_reward_claimed',
                    field=models.BooleanField(default=False),
                ),
            ],
            database_operations=[]
        ),
    ]
