# Generated by Django 5.2.16 on 2026-08-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_agentbackup_agent_google_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='agent_show_achievements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='agent_show_certificates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='agent_show_claims_stats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='agent_show_client_base',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='agent_show_contact_info',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='agent_show_experience',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='agent_show_gallery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='agent_show_languages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='agent_show_ratings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='agent_show_reviews',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='agent_show_social_media',
            field=models.BooleanField(default=True),
        ),
    ]
