# Generated by Django 5.2.16 on 2026-08-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_agentbackup_agent_google_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='show_claims_stats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='show_client_base',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='show_contact_info',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='show_experience',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='show_gallery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='show_languages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='show_ratings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='show_social_links',
            field=models.BooleanField(default=True),
        ),
    ]
