# Generated by Django 5.2.16 on 2026-08-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_add_participant_facebook_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=191)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'agent_notifications',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('insurance_segments', models.JSONField(default=list)),
                ('pincode', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('promocode', models.CharField(blank=True, max_length=255, null=True)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('selected_plan', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='incomplete', max_length=20)),
                ('payment_status', models.CharField(default='pending', max_length=255)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'event_registrations',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FavoriteAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'favorite_agents',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=191)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('phone_number', models.CharField(max_length=191)),
                ('have_insurance', models.CharField(blank=True, max_length=5, null=True)),
                ('insurance_products', models.JSONField(blank=True, null=True)),
                ('insurance_planning', models.CharField(blank=True, max_length=191, null=True)),
                ('mutual_fund', models.CharField(blank=True, max_length=5, null=True)),
                ('mf_plan', models.CharField(blank=True, max_length=191, null=True)),
                ('thank_my_padosi', models.CharField(blank=True, max_length=191, null=True)),
                ('thank_my_padosi_for', models.TextField(blank=True, null=True)),
                ('participant_shared', models.CharField(default='No', max_length=5)),
                ('shareable_id', models.CharField(blank=True, max_length=191, null=True)),
                ('registration_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('facebook_access_token', models.TextField(blank=True, null=True)),
                ('facebook_user_id', models.CharField(blank=True, max_length=191, null=True)),
                ('facebook_post_id', models.CharField(blank=True, max_length=191, null=True)),
                ('facebook_post_url', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='registered', max_length=50)),
                ('manual_share', models.BooleanField(default=False)),
                ('screenshot_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'participants',
                'managed': False,
            },
        ),
    ]
