# Generated by Django 5.2.16 on 2026-08-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_agentcareertimeline_suggestion_key'),
        ('agents', '0016_agent_payment_method_agent_payment_recorded_at_and_more'),
    ]

    operations = [
    ]
