# Generated by Django 5.2.16 on 2026-08-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_merge_20260810_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'investment_types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='agentdraft',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentcareertimeline',
            name='suggestion_key',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
