# Generated by Django 5.2.16 on 2026-08-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0018_investmenttype_agentdraft_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('html_code', models.TextField(blank=True, default='')),
                ('actual_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('show_agent_certificate', models.BooleanField(default=True)),
                ('show_career_timeline', models.BooleanField(default=True)),
                ('show_professional_bio', models.BooleanField(default=True)),
                ('show_social_media', models.BooleanField(default=True)),
                ('show_new_business_leads', models.BooleanField(default=True)),
                ('show_portfolio', models.BooleanField(default=True)),
                ('show_claim_support', models.BooleanField(default=True)),
                ('show_companies', models.BooleanField(default=True)),
                ('show_achievement', models.BooleanField(default=True)),
                ('show_lead_status', models.BooleanField(default=True)),
                ('show_sales_insights', models.BooleanField(default=True)),
                ('show_recent_leads', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_plans',
                'managed': True,
            },
        ),
    ]
