# Generated by Django 5.2.16 on 2026-08-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0019_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='show_profile_section',
            field=models.BooleanField(default=True),
        ),
    ]
