# Generated by Django 5.2.16 on 2026-08-18 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0021_subscriptionplan_is_listed_in_directory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlanProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_key', models.CharField(max_length=50)),
                ('discount_unlocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.agentdraft')),
            ],
            options={
                'db_table': 'user_plan_progress',
                'managed': True,
            },
        ),
    ]
