# Generated by Django 5.2.16 on 2026-08-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0022_userplanprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='badge_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='color_theme',
            field=models.CharField(default='starter-theme', max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
