# Generated by Django 5.2.16 on 2026-09-07 13:46 (hand-fixed for BIGINT UNSIGNED + idempotency)
#
# Both tables use RunSQL with IF NOT EXISTS:
# - agent_search_events: idempotent (partially created in a failed first run)
# - agent_card_impressions: BIGINT UNSIGNED agent_id to match agents.id (Laravel legacy)

import django.db.models.deletion
from django.db import migrations, models


def create_analytics_tables(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == 'mysql':
        with connection.cursor() as cursor:
            cursor.execute("""
            CREATE TABLE IF NOT EXISTS `agent_search_events` (
                `id`          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                `search_date` DATE            NOT NULL,
                `pincode`     VARCHAR(10)     NULL,
                `event_count` INT             NOT NULL DEFAULT 1,
                `created_at`  DATETIME(6)     NOT NULL,
                `updated_at`  DATETIME(6)     NOT NULL,
                PRIMARY KEY (`id`),
                UNIQUE KEY `ase_date_pincode` (`search_date`, `pincode`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
            """)
            cursor.execute("""
            CREATE TABLE IF NOT EXISTS `agent_card_impressions` (
                `id`               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                `agent_id`         BIGINT UNSIGNED NOT NULL,
                `impression_date`  DATE            NOT NULL,
                `search_pincode`   VARCHAR(10)     NULL,
                `impression_count` INT             NOT NULL DEFAULT 1,
                `created_at`       DATETIME(6)     NOT NULL,
                `updated_at`       DATETIME(6)     NOT NULL,
                PRIMARY KEY (`id`),
                UNIQUE KEY `aci_agent_date_pincode` (`agent_id`, `impression_date`, `search_pincode`),
                CONSTRAINT `aci_agent_fk`
                    FOREIGN KEY (`agent_id`) REFERENCES `agents` (`id`)
                    ON DELETE CASCADE
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
            """)
    else:
        with connection.cursor() as cursor:
            cursor.execute("""
            CREATE TABLE IF NOT EXISTS agent_search_events (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                search_date DATE NOT NULL,
                pincode VARCHAR(10) NULL,
                event_count INTEGER NOT NULL DEFAULT 1,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL,
                UNIQUE (search_date, pincode)
            );
            """)
            cursor.execute("""
            CREATE TABLE IF NOT EXISTS agent_card_impressions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                agent_id INTEGER NOT NULL,
                impression_date DATE NOT NULL,
                search_pincode VARCHAR(10) NULL,
                impression_count INTEGER NOT NULL DEFAULT 1,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL,
                UNIQUE (agent_id, impression_date, search_pincode)
            );
            """)


def drop_analytics_tables(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS agent_card_impressions;")
        cursor.execute("DROP TABLE IF EXISTS agent_search_events;")


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0025_subscriptionplan_display_fields_safe'),
    ]

    operations = [
        migrations.RunPython(create_analytics_tables, reverse_code=drop_analytics_tables),

        # ── Register both models in Django's migration state ───────────────
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='AgentSearchEvent',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('search_date', models.DateField()),
                        ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                        ('event_count', models.IntegerField(default=1)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'db_table': 'agent_search_events',
                        'managed': True,
                        'unique_together': {('search_date', 'pincode')},
                    },
                ),
                migrations.CreateModel(
                    name='AgentCardImpression',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('impression_date', models.DateField()),
                        ('search_pincode', models.CharField(blank=True, max_length=10, null=True)),
                        ('impression_count', models.IntegerField(default=1)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('agent', models.ForeignKey(
                            db_constraint=False,
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='card_impressions',
                            to='agents.agent',
                        )),
                    ],
                    options={
                        'db_table': 'agent_card_impressions',
                        'managed': True,
                        'unique_together': {('agent', 'impression_date', 'search_pincode')},
                    },
                ),
            ],
            database_operations=[],  # Tables already created by RunSQL above
        ),
    ]
