# Generated by Django 5.2.16 on 2026-09-15 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0027_registrationactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdraft',
            name='distributor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentdraft',
            name='referred_by_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
