# Generated by Django 5.2.16 on 2026-10-01 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0031_planupgradehandoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='event_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='mobile',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='agent',
            name='referred_by_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.CharField(db_index=True, default='incomplete', max_length=50),
        ),
        migrations.AlterField(
            model_name='agentcardimpression',
            name='agent',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='card_impressions', to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='agentdraft',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
