# Generated by Django 5.2.16 on 2026-10-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0032_alter_agent_event_id_alter_agent_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsubscription',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agentsubscription',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='agent_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
