# Generated by Django 5.2.16 on 2026-10-02 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0033_index_razorpay_lookup_columns'),
        ('agents', '0033_merge_plan_offer_and_registration_indexes'),
    ]

    operations = [
    ]
