# Generated by Django 5.2.16 on 2026-10-04 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0034_merge_20261002_0056'),
    ]

    # State only (2026-10-04): the models now declare db_constraint=False on
    # every Agent foreign key. Production's legacy agents.id type cannot take
    # a Django FK (MariaDB errno 150), so no SQL is run here: existing
    # constraints, if any, stay as they are, and dropping a missing one would
    # fail the deploy.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='agentachievementphoto',
                    name='agent',
                    field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='achievementPhotos', to='agents.agent'),
                ),
                migrations.AlterField(
                    model_name='agentcareertimeline',
                    name='agent',
                    field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='careerTimelines', to='agents.agent'),
                ),
                migrations.AlterField(
                    model_name='agentdevicetoken',
                    name='agent',
                    field=models.ForeignKey(db_column='agent_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='agents.agent'),
                ),
                migrations.AlterField(
                    model_name='agentfamilylicense',
                    name='agent',
                    field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='familyLicenses', to='agents.agent'),
                ),
                migrations.AlterField(
                    model_name='agentinsurancesegment',
                    name='agent',
                    field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='insuranceSegments', to='agents.agent'),
                ),
                migrations.AlterField(
                    model_name='agentlead',
                    name='agent',
                    field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='agents.agent'),
                ),
                migrations.AlterField(
                    model_name='agentleadpreference',
                    name='agent',
                    field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='leadPreferences', to='agents.agent'),
                ),
                migrations.AlterField(
                    model_name='agentperformancestat',
                    name='agent',
                    field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='performanceStats', to='agents.agent'),
                ),
                migrations.AlterField(
                    model_name='agentportfolio',
                    name='agent',
                    field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='agents.agent'),
                ),
                migrations.AlterField(
                    model_name='agentproductexpertise',
                    name='agent',
                    field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='productExpertise', to='agents.agent'),
                ),
                migrations.AlterField(
                    model_name='agentprofile',
                    name='agent',
                    field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='agents.agent'),
                ),
                migrations.AlterField(
                    model_name='agentprofileeditlog',
                    name='agent',
                    field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='agents.agent'),
                ),
                migrations.AlterField(
                    model_name='agentprofileview',
                    name='agent',
                    field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to='agents.agent'),
                ),
                migrations.AlterField(
                    model_name='agentreview',
                    name='agent',
                    field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='agents.agent'),
                ),
                migrations.AlterField(
                    model_name='agentsubscription',
                    name='agent',
                    field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='agents.agent'),
                ),
                migrations.AlterField(
                    model_name='invoice',
                    name='agent',
                    field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='agents.agent'),
                ),
    
            ],
        ),
    ]
