# Generated by Django 6.0.2 on 2026-07-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_qr_files_and_approvals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersessiondata',
            name='session',
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='adminbroadcast',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='agentapprovalrequest',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='agentservicepincode',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pincodeimportlog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='qrfile',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='referralcode',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='referralusage',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='securitythreatlog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
        migrations.DeleteModel(
            name='UserSessionData',
        ),
    ]
