# Generated by Django 5.2.16 on 2026-09-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_apilog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminbroadcast',
            options={'managed': True},
        ),
    ]
