# Generated by Django 5.2.16 on 2026-10-09 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_alter_adminbroadcast_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20, unique=True)),
                ('latest_version', models.CharField(help_text='Newest version available on the store, e.g. 1.4.0', max_length=20)),
                ('min_supported_version', models.CharField(help_text='Oldest version allowed to keep using the app, e.g. 1.2.0', max_length=20)),
                ('force_update', models.BooleanField(default=False, help_text='If ON, apps below min_supported_version are hard-blocked.')),
                ('update_message', models.CharField(blank=True, default='', help_text='Message shown on the update prompt.', max_length=255)),
                ('store_url', models.CharField(blank=True, default='', help_text='Play Store / App Store link.', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='If OFF, the API reports no update for this platform.')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'app_versions',
                'ordering': ['platform'],
            },
        ),
    ]
