# Generated by Django 5.2.16 on 2026-10-09 15:26

import datetime

import django.db.models.deletion
from django.db import connection, migrations, models


def _column_exists(schema_editor, table, column):
    with schema_editor.connection.cursor() as cursor:
        try:
            names = {
                col.name
                for col in connection.introspection.get_table_description(cursor, table)
            }
            return column in names
        except Exception:
            return False


def _table_exists(schema_editor, table):
    with schema_editor.connection.cursor() as cursor:
        return table in connection.introspection.table_names(cursor)


def apply_contact_ticketing_schema(apps, schema_editor):
    """Add ticketing columns/table when missing (safe on partially migrated DBs)."""
    submissions = 'contact_submissions'
    with schema_editor.connection.cursor() as cursor:
        if not _column_exists(schema_editor, submissions, 'assigned_admin_id'):
            if schema_editor.connection.vendor == 'mysql':
                cursor.execute(
                    f'ALTER TABLE {submissions} ADD COLUMN assigned_admin_id INT NULL'
                )
            else:
                cursor.execute(
                    f'ALTER TABLE {submissions} ADD COLUMN assigned_admin_id INTEGER NULL'
                )
        if not _column_exists(schema_editor, submissions, 'last_reply_at'):
            if schema_editor.connection.vendor == 'mysql':
                cursor.execute(
                    f'ALTER TABLE {submissions} ADD COLUMN last_reply_at DATETIME NULL'
                )
            else:
                cursor.execute(
                    f'ALTER TABLE {submissions} ADD COLUMN last_reply_at datetime NULL'
                )
        if not _column_exists(schema_editor, submissions, 'priority'):
            if schema_editor.connection.vendor == 'mysql':
                cursor.execute(
                    f"ALTER TABLE {submissions} ADD COLUMN priority VARCHAR(20) NOT NULL DEFAULT 'normal'"
                )
            else:
                cursor.execute(
                    f"ALTER TABLE {submissions} ADD COLUMN priority varchar(20) NOT NULL DEFAULT 'normal'"
                )

    if not _table_exists(schema_editor, 'contact_replies'):
        with schema_editor.connection.cursor() as cursor:
            if schema_editor.connection.vendor == 'mysql':
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS contact_replies (
                        id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                        submission_id BIGINT NOT NULL,
                        admin_id INT NULL,
                        admin_name VARCHAR(255) NOT NULL DEFAULT '',
                        message LONGTEXT NOT NULL,
                        is_internal_note TINYINT(1) NOT NULL DEFAULT 0,
                        emailed TINYINT(1) NOT NULL DEFAULT 0,
                        created_at DATETIME NOT NULL,
                        CONSTRAINT fk_contact_replies_submission
                            FOREIGN KEY (submission_id)
                            REFERENCES contact_submissions(id)
                            ON DELETE CASCADE
                    )
                """)
            else:
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS contact_replies (
                        id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                        submission_id INTEGER NOT NULL
                            REFERENCES contact_submissions(id) DEFERRABLE INITIALLY DEFERRED,
                        admin_id INTEGER NULL,
                        admin_name VARCHAR(255) NOT NULL DEFAULT '',
                        message TEXT NOT NULL,
                        is_internal_note BOOLEAN NOT NULL DEFAULT 0,
                        emailed BOOLEAN NOT NULL DEFAULT 0,
                        created_at DATETIME NOT NULL
                    )
                """)


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_appversion'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='contactsubmission',
                    name='assigned_admin_id',
                    field=models.IntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='contactsubmission',
                    name='last_reply_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='contactsubmission',
                    name='priority',
                    field=models.CharField(
                        choices=[
                            ('low', 'Low'),
                            ('normal', 'Normal'),
                            ('high', 'High'),
                            ('urgent', 'Urgent'),
                        ],
                        default='normal',
                        max_length=20,
                    ),
                ),
                migrations.AlterField(
                    model_name='contactsubmission',
                    name='status',
                    field=models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('in_progress', 'In Progress'),
                            ('replied', 'Replied'),
                            ('closed', 'Closed'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                migrations.CreateModel(
                    name='ContactReply',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('admin_id', models.IntegerField(blank=True, null=True)),
                        ('admin_name', models.CharField(blank=True, default='', max_length=255)),
                        ('message', models.TextField()),
                        ('is_internal_note', models.BooleanField(default=False)),
                        ('emailed', models.BooleanField(default=False)),
                        ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                        (
                            'submission',
                            models.ForeignKey(
                                db_column='submission_id',
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='replies',
                                to='admin_panel.contactsubmission',
                            ),
                        ),
                    ],
                    options={
                        'db_table': 'contact_replies',
                        'ordering': ['created_at'],
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    apply_contact_ticketing_schema,
                    migrations.RunPython.noop,
                ),
            ],
        ),
    ]
